/* 
https://www.dawaadost.com/ur/medicine/udapa-trio-tablet-er-10s
https://www.dawaadost.com/ur/medicine/clarinova-250mg-tablet-10s
https://www.dawaadost.com/ur/medicine/febustat-80mg-tablet-15s
https://www.dawaadost.com/ur/medicine/igurati-25mg-tablet-10s
https://www.dawaadost.com/ur/medicine/telvok-40mg-tablet-10s
https://www.dawaadost.com/ur/medicine/bonicor-max-capsule-15s
https://www.dawaadost.com/ur/medicine/rizole-d-30mg20mg-capsule-sr-10s
https://www.dawaadost.com/ur/medicine/gluxit-trio-10mg100mg500mg-tablet-15s
https://www.dawaadost.com/ur/medicine/coralan-od-10mg-tablet-10s
https://www.dawaadost.com/ur/medicine/cilniheal-10-tablet
https://www.dawaadost.com/ur/medicine/fixit-d3-capsule-8s
https://www.dawaadost.com/ur/medicine/ericap-500mg-tablet-10s
https://www.dawaadost.com/ur/medicine/lubritex-0.5wv-eye-drop-10ml
https://www.dawaadost.com/ur/medicine/lobp-t-50mg40mg-tablet-10s
https://www.dawaadost.com/ur/medicine/oxramet-s-xr-1000mg-tablet-7s
https://www.dawaadost.com/ur/medicine/vibucin-forte-tablet-100s
https://www.dawaadost.com/ur/medicine/jbtor-plus-ls-10mg25mg-tablet-10s
https://www.dawaadost.com/ur/medicine/x-glar-100iu-injection-5ml
https://www.dawaadost.com/ur/medicine/oflin-o-200mg500mg-tablet-10s
https://www.dawaadost.com/ur/medicine/sitabest-100mg-tablet-10s
https://www.dawaadost.com/ur/medicine/bisolong-2.5mg-tablet-10s
https://www.dawaadost.com/ur/medicine/apivas-2.5mg-tablet-10s
https://www.dawaadost.com/ur/medicine/sitaxa-m-500mg50mg-tablet-15s
https://www.dawaadost.com/ur/medicine/renopress-xl-2.5mg-tablet
https://www.dawaadost.com/ur/medicine/dapahenz-sm-1000mg-tablet-10s
https://www.dawaadost.com/ur/medicine/prucros-40mg-tablet-10s
https://www.dawaadost.com/ur/medicine/justoza-5mg-tablet-15s
https://www.dawaadost.com/ur/medicine/zycal-d-250500-tablet-10s
https://www.dawaadost.com/ur/medicine/sovalmat-333mg145mg-tablet-cr-10s
https://www.dawaadost.com/ur/medicine/d-cold-total-tablet-12s
https://www.dawaadost.com/ur/medicine/rabipath-d-30mg20mg-capsule-sr-10s
https://www.dawaadost.com/ur/medicine/dovy-m-80mg250mg-tablet-10s
https://www.dawaadost.com/ur/medicine/stalix-dm-10mg100mg500mg-tablet-10s
https://www.dawaadost.com/ur/medicine/moxikoz-400mg-tablet-6s
https://www.dawaadost.com/ur/medicine/zomelis-dm-forte-tablet-10s
https://www.dawaadost.com/ur/medicine/ezeepam-5mg-tablet-10s
https://www.dawaadost.com/ur/medicine/farobact-300mg-tablet-er-10s


*/
